name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t bahalek/midt:latest .

      - name: Push Docker image to Docker Hub
        run: docker push bahalek/midt:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: |
          ssh -i key.pem ec2-user@<16.171.160.69> <<EOF
          docker pull bahalek/midt:latest
          docker run -d -p 80:80 bahalek/midt:latest
          EOF
