name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t bahalek/midt:latest .

      - name: Push Docker image to Docker Hub
        run: docker push bahalek/midt:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker container on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker stop midt true
            docker rm midt  true
            docker pull bahalek/midt:latest
            docker run -d -p 5000:5000 --name midt bahalek.midt:latest
